kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kuku
  namespace: argocd
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem