apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-apps
  namespace: gitops-infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/reggie-k/gitops-demo-argocd.git'
    path: argo-resources/user-apps
    targetRevision: master
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitops-infra
  syncPolicy:
    automated:
      selfHeal: true

